import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>McAsks</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className={styles.main}>
        <section className={styles.section}>
        <div className={styles.triangleTopLeft}></div>
          <div style={{display: 'flex', flexDirection:"column", justifyContent: 'center'}}>
            <h1 className={styles.title}>You ask,</h1>
            <h1 className={styles.title2}>We answer</h1>
            <br></br>
            <button className={styles.button}>TRY FOR FREE &rarr;</button>
          </div>
          <div><img src="/phone.png" alt="phone mockup" style={{marginTop:"1rem",width: '400px'}}/></div>
        </section>

        <section className={styles.grid}>
          <div>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </div>

          <div>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </div>

          <div>
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </div>
        </section>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
